src/objects/Business_Role__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Short Description of Business Role</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Business Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Business_Role_Access__c.object
<CustomObject>
    <fields>
        <fullName>Business_Role__c</fullName>
        <label>Business Role</label>
        <referenceTo>Business_Role__c</referenceTo>
        <relationshipLabel>Business Role Accesses</relationshipLabel>
        <relationshipName>Business_Role_Accesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Business Role Access</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Role Accesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Business_Role_Member__c.object
<CustomObject>
    <fields>
        <fullName>Business_Role__c</fullName>
        <label>Business Role</label>
        <referenceTo>Business_Role__c</referenceTo>
        <relationshipLabel>Business Role Members</relationshipLabel>
        <relationshipName>Business_Role_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Business Role Member</label>
    <nameField>
        <displayFormat>BRM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Role Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Business_Role_Member_Access__c.object
<CustomObject>
    <fields>
        <fullName>Business_Role_Access__c</fullName>
        <label>Business Role Access</label>
        <referenceTo>Business_Role_Access__c</referenceTo>
        <relationshipLabel>Business Role Member Accesses</relationshipLabel>
        <relationshipName>Business_Role_Member_Accesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Business_Role_Member__c</fullName>
        <label>Business Role Member</label>
        <referenceTo>Business_Role_Member__c</referenceTo>
        <relationshipLabel>Business Role Member Accesses</relationshipLabel>
        <relationshipName>Business_Role_Member_Accesses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Business_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Role</label>
        <referenceTo>Business_Role__c</referenceTo>
        <relationshipLabel>Business Role Member Accesses</relationshipLabel>
        <relationshipName>Business_Role_Member_Accesses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Business Role Member Access</label>
    <nameField>
        <displayFormat>BRMA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Role Member Accesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Business_Role_Access__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Role Access</label>
        <referenceTo>Business_Role_Access__c</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Role_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Role Member</label>
        <referenceTo>Business_Role_Member__c</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Role</label>
        <referenceTo>Business_Role__c</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BRMLogUtil.cls
public with sharing class BRMLogUtil implements Queueable {
    private transient List<Business_Role_Member_Access__c> operationRecords;
    private transient List<DMLResult> databaseResults;
    private List<Error_Log__c> newErrorLogs;
    
    public BRMLogUtil() {
        newErrorLogs = new List<Error_Log__c>();
        operationRecords = new List<Business_Role_Member_Access__c>();
        databaseResults = new List<DMLResult>();
    }
    
    public BRMLogUtil addResults(List<Business_Role_Member_Access__c> recs, List<Object> results) {
        operationRecords.addAll(recs);
        databaseResults.addAll(DMLResult.asDMLResults(results));
        return this;
    }
    
    public BRMLogUtil addErrorLogs(List<Error_Log__c> logs) {
        newErrorLogs.addAll(logs);
        return this;
    }
    
    public void setupErrorLogs() {
        Integer i = 0;
        
        for(DMLResult r : databaseResults) {
            if(!r.isSuccess()) {
                Error_Log__c el = new Error_Log__c(Business_Role__c = operationRecords.get(i).Business_Role__c, 
                                                   Business_Role_Access__c = operationRecords.get(i).Business_Role_Access__c, 
                                                   Business_Role_Member__c = operationRecords.get(i).Business_Role_Member__c);
                
                for(DMLResult.Error e : r.getErrors()) {
                    el.Description__c = (el.Description__c == null ? '' : el.Description__c) + e.getStatusCode() + ': ' + e.getMessage() + '\r\n'; 
                }
                
                newErrorLogs.add(el);
            }
            
            i++;
        }
        
        if(!newErrorLogs.isEmpty() && !Test.isRunningTest()) {
        	System.enqueueJob(this);
        } else if(!newErrorLogs.isEmpty() && Test.isRunningTest()) {
            System.runAs(new User(Id = UserInfo.getUserId())) {
                execute(null);
            }
        }
    }
    
    private void insertErrorLogs() {
        Map<Id, Boolean> roleExistMap = new Map<Id, Boolean>();
        Map<Id, Boolean> accessExistMap = new Map<Id, Boolean>();
        Map<Id, Boolean> memberExistMap = new Map<Id, Boolean>();
        
        for(Error_Log__c el : newErrorLogs) {
            roleExistMap.put(el.Business_Role__c, false);
            accessExistMap.put(el.Business_Role_Access__c, false);
            memberExistMap.put(el.Business_Role_Member__c, false);
        }
        
        for(Business_Role__c br : [Select Id from Business_Role__c where Id in :roleExistMap.keySet()]) {
            roleExistMap.put(br.Id, true);
        }
        
        for(Business_Role_Access__c bra : [Select Id from Business_Role_Access__c where Id in :accessExistMap.keySet()]) {
            accessExistMap.put(bra.Id, true);
        }
        
        for(Business_Role_Member__c brm : [Select Id from Business_Role_Member__c where Id in :memberExistMap.keySet()]) {
            memberExistMap.put(brm.Id, true);
        }
        
        for(Error_Log__c el : newErrorLogs) {
            if(roleExistMap.get(el.Business_Role__c) == false) {
                el.Business_Role__c = null;
            }
            
            if(accessExistMap.get(el.Business_Role_Access__c) == false) {
                el.Business_Role_Access__c = null;
            }
            
            if(memberExistMap.get(el.Business_Role_Member__c) == false) {
                el.Business_Role_Member__c = null;
            }
        }
        
        Database.insert(newErrorLogs);
    }
    
    public void execute(QueueableContext context) {
        insertErrorLogs();
    }
}